### ISSUE TITLE
Hello Please Help

### ISSUE THREAD

**Issue by tamon504** [wanghaisheng/get-tiktok-user-video-list#1]
how to use them.? i mean where to enter douyin user profile and how to start grab the video list..? any shorts tutorials.?

**Comment by wanghaisheng** [comment]
are you looking for a coding solution 
later on i will provide a nocoding service where you can input user  profile url to get all of videos

**Comment by tamon504** [comment]
yes where to get them, or just simple tutor to use this python script

**Comment by tamon504** [comment]
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MOLAJO\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\douyin\douyin-api.py", line 83, in <module>
    main("https://www.douyin.com/user/MS4wLjABAAAAfmFMtLEnjUKr9pxnB8KK9bpDbSOSdcRaDm5iILschZU")
  File "C:\Python\douyin\douyin-api.py", line 65, in main
    data, max_cursor = get_data(uid=uid, max_cursor=max_cursor)
  File "C:\Python\douyin\douyin-api.py", line 20, in get_data
    data_json = API_Call(uid=uid, max_cursor=max_cursor)
  File "C:\Python\douyin\douyin-api.py", line 15, in API_Call
    return data.json()
  File "C:\Users\MOLAJO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

im getting this error where trying ur script whats the problem

**Comment by wanghaisheng** [comment]
try this
[douyin-pl.py](https://github.com/wanghaisheng/get-tiktok-user-video-list/blob/main/douyin-pl.py)

i dont think  douyin-api.py works
